### ISSUE TITLE
Upon unpausing the demos, the RNG/noise state is changed

### ISSUE THREAD

**Issue by Zireael07** [jordwest/cavernos#6]
Most noticeable in the Matrix demo, although it's the same in the Perlin, too.

**Comment by jordwest** [comment]
Ah, are you sure it's the RNG seed?

It probably looks like this because the `frame` function gets passed the `dt` - delta time - since the last frame. Because in the example this delta time is used to increment the position of the noise, if it has been several seconds since the last frame (like after frames have been paused for a few seconds) then the noise position is incremented by a bigger jump so it appears like a different texture. But if you pause for shorter periods, you'll see that it only jumps a little.

Applications will need to deal with this on their own if they're dependent on that time - as it can happen without pausing too. For example, if the user hides the tab in their browser, the browser will stop animating and thus we won't be calling the `frame` function. It's up to the app to decide whether to discard large chunks of time between frames or not.

**Comment by Zireael07** [comment]
IMHO incrementing dt when paused is definitely going to be seen as buggy. We can't affect the behavior when hiding the tab, but incrementing dt when paused is just... not done.

**Comment by jordwest** [comment]
Let me clarify a bit. The pause button is really more of a debug tool. It's not intended for a user to pause a game, rather it's pausing execution of the webassembly. If a game for example wants a pause function for users to press, it can implement that itself with some user interaction.

Since it's just a debug tool, I don't really want to add some special logic to handle that pause button differently than hiding the browser tab. I'll most likely remove the button in production builds at some point anyway.
