### ISSUE TITLE
README instructions to run example aren't complete

### ISSUE THREAD

**Issue by Zireael07** [jordwest/cavernos#7]
I have ran the .sh as instructed.
Problems:
1) the output WASM does not have the _optimized suffix, at least not on Rust 1.47.0, I had to manually copy it over
2) more worryingly, the host js does not build - something about parcel? Parcel requirement is not called out in the README

**Comment by jordwest** [comment]
Fixed in 17876a8b3b0aaa7a34784287b19001d0df95259a

> 1. the output WASM does not have the _optimized suffix, at least not on Rust 1.47.0, I had to manually copy it over

There's a couple extra dependencies you'll need to optimize the wasm:

 - [Binaryen](https://github.com/WebAssembly/binaryen) for the `wasm-opt` tool
 - [wabt](https://github.com/WebAssembly/wabt) for the `wasm-strip` tool

> 2. more worryingly, the host js does not build - something about parcel? Parcel requirement is not called out in the README

Parcel should now be pulled in as part of the build process
